### DISCUSSION TITLE
@alwatr/font

### DISCUSSION THREAD

**Discussion by alimd** [AliMD/alwatr#108] [Ideas]
Make font storage over CDN with CSS usage best practices
Somting like http://alimd.github.io/1fonts/demo/

**Comment by alimd** [comment]
The best arabic/persian fonts I know.

1. [Noto Sans Arabic](https://fonts.google.com/noto/specimen/Noto+Sans+Arabic?noto.region=IQ&noto.lang=ar_Arab)
2. [Noto Naskh Arabic](https://fonts.google.com/noto/specimen/Noto+Naskh+Arabic?noto.region=IQ&noto.lang=ar_Arab)
3. [Noto Kufi Arabic](https://fonts.google.com/noto/specimen/Noto+Kufi+Arabic?noto.region=IQ&noto.lang=ar_Arab)
4. [Dana](https://fontiran.com/%D9%81%D9%88%D9%86%D8%AA-%D8%AF%D8%A7%D9%86%D8%A7-%D8%AD%D8%B1%D9%81%D9%87%D8%A7%DB%8C/)
5. [Estedad](https://fontjo.com/%D9%81%D9%88%D9%86%D8%AA-%D9%81%D8%A7%D8%B1%D8%B3%DB%8C-%D8%A7%D8%B3%D8%AA%D8%B9%D8%AF%D8%A7%D8%AF-estedad/)
6. [Iran Sans X](https://fontiran.com/%d8%ae%d8%a7%d9%86%d9%88%d8%a7%d8%af%d9%87-%d9%81%d9%88%d9%86%d8%aa-%d8%a7%db%8c%d8%b1%d8%a7%d9%86-%d8%b3%d9%86-%d8%b3%d8%b1%db%8c%d9%81-iran-sans-%d9%be%d9%86%d8%ac-%d9%88%d8%b2%d9%86-%d9%87%d9%85-2/)
7. [Iran Sans DN](https://fontiran.com/%D9%81%D9%88%D9%86%D8%AA-%D8%A7%DB%8C%D8%B1%D8%A7%D9%86-%D8%B3%D9%86%D8%B3-%D8%AF%D8%B3%D8%AA-%D9%86%D9%88%DB%8C%D8%B3-iransansdn/)
8. [Iran Sharp](https://fontiran.com/%D9%81%D9%88%D9%86%D8%AA-%D8%A7%DB%8C%D8%B1%D8%A7%D9%86-%D8%B4%D8%A7%D8%B1%D9%BE-iran-sharp-%D8%AD%D8%A7%D9%88%DB%8C-%D9%81%D9%88%D9%86%D8%AA-%D9%85%D9%88%D8%A8%D8%A7%DB%8C%D9%84-%D9%88%D8%A8/)
9. [Iran Yekan](https://fontiran.com/%D9%81%D9%88%D9%86%D8%AA-%D8%A7%DB%8C%D8%B1%D8%A7%D9%86-%DB%8C%DA%A9%D8%A7%D9%86-iran-yekan/)
10. [Parastoo](https://rastikerdar.github.io/parastoo-font/)
11. [Vazir Matn](https://rastikerdar.github.io/vazirmatn/)
12. [Sahel](https://rastikerdar.github.io/sahel-font/)
13. [Yekan Bakh](https://rezagraphic.ir/16997/%D8%AF%D8%A7%D9%86%D9%84%D9%88%D8%AF-%D8%B1%D8%A7%DB%8C%DA%AF%D8%A7%D9%86-%D9%81%D9%88%D9%86%D8%AA-%D9%81%D8%A7%D8%B1%D8%B3%DB%8C-%DB%8C%DA%A9%D8%A7%D9%86-%D8%A8%D8%AE-yekan-bakh-font/)

**Comment by alimd** [comment]
Khafan Collections

1. https://rastikerdar.github.io/compare-fonts
2. https://fontiran.com/lab/
3. https://rbakhtiarifard.ir/typefaces
4. https://daskhat.dexignresources.com/

**Comment by alimd** [comment]
Best practice for font usage

Define all fonts in single css file like this and use `local` in src befor `url`

```css
@font-face {
  font-family: "roboto";
  font-style: normal;
  font-weight: 100;
  src: local("roboto thin"), local("roboto-thin"), url("roboto-v2.1/roboto-thin.woff") format("woff");
  font-display: block;
}

@font-face {
  font-family: "roboto";
  font-style: normal;
  font-weight: 300;
  src: local("roboto light"), local("roboto-light"), url("roboto-v2.1/roboto-light.woff") format("woff");
  font-display: block;
}

@font-face {
  font-family: "roboto";
  font-style: normal;
  font-weight: 400;
  src: local("roboto regular"), local("roboto-regular"), url("roboto-v2.1/roboto-regular.woff") format("woff");
  font-display: block;
}
```

Use this trick to link the external css file to prevent render blocking

```html
<link rel="preload" href="https://cdn.jsdelivr.net/npm/@alwatr/font@1.0.0/font.css" as="style" crossorigin />
<link rel="preload" href="https://cdn.jsdelivr.net/npm/@alwatr/font@1.0.0/fonts/roboto/roboto-thin.woff" as="font" type="font/woff" crossorigin />
<link rel="preload" href="https://cdn.jsdelivr.net/npm/@alwatr/font@1.0.0/fonts/..." as="font" type="font/woff" crossorigin />

...

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@alwatr/font@1.0.0/font.css" media="print" onload="this.onload=null; this.media='all'"/>
```

Use default fonts in body in index.html root (not sperate css file)

```css
body {
  font-family: "roboto", "iranyekan", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
  -moz-osx-font-smoothing: grayscale;
  -webkit-font-smoothing: antialiased;
  transform: translateZ(0);
  text-rendering: optimizeLegibility;
  word-wrap: break-word;
  text-size-adjust: none;
}
```

**Reply by alimd** [reply]
Base on [MDN FAQ about prefetching](https://developer.mozilla.org/en-US/docs/Web/HTTP/Link_prefetching_FAQ) and [MDN link type preload](https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types/preload) I think prefetch is wrong for fonts because:

> prefetch isn't useful for the current page! In addition, browsers will give prefetch resources a lower priority than preload ones — the current page is more important than the next.

**Reply by alimd** [reply]
```html
<link rel="preload" href="fonts/mywebfont.woff2" as="font" type="font/woff2" crossorigin>
```

**Reply by alimd** [reply]
https://bundlers.tooling.report/non-js-resources/html/preload-assets/

**Reply by asmanp2012** [reply]
این که خوده رستگار این کار رو کرده خیلی جالبه کاش همشون اینجوری بودن
https://www.npmjs.com/package/vazirmatn
https://www.npmjs.com/package/sahel-font
https://www.npmjs.com/package/tanha-font

```html
<link href="https://cdn.jsdelivr.net/gh/rastikerdar/vazirmatn@v32.101/Vazirmatn-font-face.css" rel="stylesheet" type="text/css" />
```

```css
body {
    font-family: Vazirmatn, sans-serif;
}
```

**Comment by berenjian** [comment]
Some other open-source fonts:

1. [Mikhak](https://aminabedi68.github.io/Mikhak/)
2. [Shabnam](https://rastikerdar.github.io/shabnam-font/)
3. [Samim](https://rastikerdar.github.io/samim-font/)
4. [Gandom](https://rastikerdar.github.io/gandom-font/)
5. [Tanha](https://rastikerdar.github.io/tanha-font/)

**Comment by alimd** [comment]
سوال کلیدی: Woff vs Woff2
این دو فونت تفاوت معناداری در حجم ندارن و چون مرور گر های قدیدمی مثل IE  ازش پشتیبانی نمیکنند حتما باید woff رو هم ارایه بدیم
حالا آیا برای مرورگر های جدید از woff2 استفاده کنیم؟ به نظرم مرورگر های جدید باید بریم سراغ variable font ها پس دیگه woff2 سنتی رو بیخیال بشیم

**Reply by alimd** [reply]
Test on Vazirmatn

Convert to woff by https://github.com/fontello/ttf2woff#usage

Result:
```sh
du -hd1
280K	./variable
740K	./woff2
792K	./woff
1.4M	./ttf
```

**Reply by sahbaee** [reply]
قطعا در آینده نه چندان دور همه به سمت variable فونت ها روی میارن.. همونطور که الان چندین فونت معروف فارسی دارن نسخه variable رو ریلیز می‌کنند.
جدا از مزایای پرفورمنسی. 
اینکه پروژه رو بروز نگه میداره.(چند سال دیگه نیاز به تغییر فرمت فونت ها نداریم) پوینت مثبتی محسوب میشه.
البته یک نکته ای که هست برای فونت های فارسی فعلا تعداد انگشت شماری نسخه variable رو دارن.

**Comment by alimd** [comment]
## Learn more about variable fonts

- https://developers.google.com/web/fundamentals/design-and-ux/typography/variable-fonts
- https://variablefonts.typenetwork.com
- https://medium.com/variable-fonts

In desktop apps

- https://theblog.adobe.com/can-variable-fonts-illustrator-cc
- https://helpx.adobe.com/nz/photoshop/using/fonts.html#variable_fonts

Online

- https://developers.google.com/fonts/docs/getting_started
- https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Fonts/Variable_Fonts_Guide
- https://developer.microsoft.com/en-us/microsoft-edge/testdrive/demos/variable-fonts

**Comment by sahbaee** [comment]
https://fonts.google.com/specimen/Lalezar#standard-styles

**Reply by alimd** [reply]
دمش گرم! رفت تو گوگل

**Reply by asmanp2012** [reply]
https://fonts.google.com/specimen/Vazirmatn

**Comment by alimd** [comment]
Arabic/Persian unicode range

```
@font-face {
  ...
  unicode-range: U+0600-06FF, U+0750-077F, U+08A0-08FF, U+FB50-FDFF, U+FE70-FEFF, U+1EE00-1EEFF;
}
```

[Font unicode blocks table](https://unicode-table.com/en/blocks/)

**Comment by alimd** [comment]
[The Font Stack](https://bitsofco.de/the-new-system-font-stack/)

My choose
```css
:root {
  --alwatr-font: "Vazirmatn",
                  -apple-system,
                  BlinkMacSystemFont,
                  "Segoe UI",
                  "Roboto",
                  "Oxygen",
                  "Ubuntu",
                  "Cantarell",
                  "Open Sans",
                  "Helvetica Neue",
                  "Arial",
                  sans-serif,
                  "Apple Color Emoji",
                  "Segoe UI Emoji",
                  "Segoe UI Symbol";
}
```
